name: Security Scan
on:
  push:
    branches:
      - 'main'
      - '*.*.x'
  
jobs:
  SecurityScan:
    runs-on: ubuntu-latest
    environment: security-scan
    steps:
      - name: Start Security Scan
        run: |
          echo "Starting Security Scan"
