name: Security Scanning

on:
  workflow_dispatch:

jobs:
  get-branches-to-scan:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.determine-branches.outputs.branches }}
    steps:
      - name: Checkout repository
        run: |
          echo "Hi there!"

  security-scan:
    runs-on: ubuntu-latest
    needs: [get-branches-to-scan]
    strategy:
      matrix:
        target: [code-editor-sagemaker-server, code-editor-server]
    steps:
      - name: Assume IAM Role
        run: |
          echo "PASS" > scan-success.txt
      
      - name: Upload Success Indicator File
        uses: actions/upload-artifact@v4
        with:
          name: scan-success
          path: scan-success.txt
          retention-days: 90
  
  # security-scan-global-dependencies:
  #   runs-on: ubuntu-latest
  #   needs: [get-branches-to-scan]
  #   strategy:
  #     matrix:
  #       target: [code-editor-sagemaker-server, code-editor-server]
  #   steps:
  #     - name: Assume IAM Role v2
  #       run: |
  #         if [ "${{ matrix.target }}" = "code-editor-server" ]; then
  #           echo "Failing for code-editor-server"
  #           exit 1
  #         fi
  #         echo "I'm still running for code-editor-sagemaker-server"
  #         sleep 1m