name: Build Linux x86 Distribution

on:
  workflow_dispatch

env:
  AWS_REGION : "us-west-2"
  DISTRO_POSTFIX: "linux-x64"

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  DistributePackage:
    runs-on: ubuntu-latest
    environment: "Build Env"
    steps:
      - name: Echo something
        run: |
          echo "Hi"
          echo "${{secrets.TEST_SECRET}}"
      - name: Create Artifact
        run: |
          echo "Hi there!" >> sample_file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{github.sha}}
          path: sample_file.txt
